### ISSUE TITLE
Nginx cannot start. Module fails to load with: pcre_fullinfo: symbol not found

### ISSUE THREAD

**Issue by boredazfcuk** [yaoweibin/ngx_http_substitutions_filter_module#44]
Hi,

I'm seeing the following error when I launch Nginx:

```
2022/05/26 16:44:23 [emerg] 1#1: dlopen() "/etc/nginx/modules/ngx_http_subs_filter_module.so" failed (Error relocating /etc/nginx/modules/ngx_http_subs_filter_module.so: pcre_fullinfo: symbol not found) in /etc/nginx/nginx.conf:6

nginx: [emerg] dlopen() "/etc/nginx/modules/ngx_http_subs_filter_module.so" failed (Error relocating /etc/nginx/modules/ngx_http_subs_filter_module.so: pcre_fullinfo: symbol not found) in /etc/nginx/nginx.conf:6
```

I see this error when building from source on both the nginx:mainline-alpine and nginx:stable-alpine offical Docker images. This was working with nginx 1.20.0, but I've recently rebuild my container with Nginx 1.22.0 and it's since then that I've seen the error.

Thanks.

**Comment by dvershinin** [comment]
@boredazfcuk it likely means that the module was compiled with PCRE1 while NGINX with PCRE2

**Comment by boredazfcuk** [comment]
Ah yeah, Dockerfile installs pcre-dev instead of pcre2-dev.

All good now.

Thanks.

**Comment by morkot** [comment]
hi @boredazfcuk could you tell me how did you solve the issue?

**Comment by boredazfcuk** [comment]
Yeah no worries. I just added it as a package. See here:

https://github.com/boredazfcuk/docker-nginx/blob/master/Dockerfile
